package diff

import (
	"fmt"
	"sort"
	"strings"

	"vitess.io/vitess/go/vt/sqlparser"

	"github.com/winebarrel/myschema/model"
	"github.com/winebarrel/myschema/parser"
)

// diffPartitions compares the partition clauses of `current` and
// `desired` (both already normalised through
// `parser.NormalizePartitionOption`, both stored on
// `model.Table.Partition` as `*string`). Returns the executable
// `ALTER TABLE … ADD/DROP PARTITION` statements, the suppressed
// drops (when `--allow-drop=partition` is unset), and an error
// for any partition diff myschema doesn't generate yet.
//
// v1 scope (this PR):
//
//   - both sides nil → no-op.
//   - both sides set, byte-equal → no-op.
//   - one side nil → error (adding / removing partitioning to/from
//     an existing table is REMOVE PARTITIONING + new PARTITION BY,
//     a future PR).
//   - partition strategy (RANGE/LIST/HASH/KEY/...COLUMNS),
//     expression, or column list differs → error (scheme change
//     is a future PR).
//   - HASH/KEY (incl. LINEAR) — partition count change goes
//     through dedicated grammar: `ADD PARTITION PARTITIONS n`
//     to grow, `COALESCE PARTITION n` to shrink. Both
//     directions are row-preserving but data-moving (rows are
//     redistributed across partitions); how much data moves
//     depends on whether the table uses regular HASH / KEY
//     (the modulus changes, so most rows shift) or LINEAR
//     HASH / LINEAR KEY (the linear-powers-of-two algorithm
//     touches only partitions adjacent to the change — much
//     faster, per the MySQL manual). The shrink path is gated
//     on `--allow-drop=partition` not because rows are lost
//     but because the slot structure changes irreversibly —
//     same "destructive / heavy" treatment as RANGE/LIST DROP.
//     Equal count = no-op. Header (Type / IsLinear /
//     KeyAlgorithm / ColList / Expr) mismatch falls through to
//     "scheme/expression differs" upstream of this branch.
//   - RANGE/LIST: definitions go through an order-preserving
//     subset diff. Pure suffix add (current's list is a prefix
//     of desired's) → ADD PARTITION. Order-preserving subset
//     drop (desired matches a same-order subsequence of
//     current) → DROP PARTITION — head, middle, and tail
//     removals are all generated, since `ALTER TABLE … DROP
//     PARTITION p1, p2` accepts a discontinuous name list.
//     Per-partition definition change of existing partitions
//     (drops + adds both non-empty AND the full catalog /
//     desired name lists line up position-by-position with the
//     same names case-insensitively) → `REORGANIZE PARTITION
//     p1, p2, … INTO (…)`. Covers `VALUES …` boundary tweaks
//     plus COMMENT / MAX_ROWS / TABLESPACE / other per-partition
//     options that round-trip through vitess's
//     PartitionDefinition formatter. Anything else (split /
//     merge / reorder / interior insert — i.e. the name lists
//     don't line up) → error so the user falls back to a hand-
//     written REORGANIZE with explicit boundaries (or a DROP+ADD
//     pair if discarding data is intended).
//
// CAVEATS.md "Partitioning" documents the user-facing rules.
func diffPartitions(fqtn string, current, desired *string, dc DropChecker) ([]string, []string, error) {
	if current == nil && desired == nil {
		return nil, nil, nil
	}
	if current != nil && desired != nil && *current == *desired {
		return nil, nil, nil
	}
	if current == nil {
		// desired adds partitioning to an unpartitioned catalog table.
		// First-time `ALTER TABLE … PARTITION BY …` generation is a
		// future PR — point the user at the right ALTER for *this*
		// direction so the manual fallback isn't backwards.
		return nil, nil, fmt.Errorf("table %s: desired SQL partitions a table that the catalog has unpartitioned; first-time ALTER TABLE … PARTITION BY … is not yet generated by myschema. Run the PARTITION BY by hand and let the next plan reconverge", fqtn)
	}
	if desired == nil {
		// desired drops partitioning from a partitioned catalog
		// table — the inverse of the case above.
		return nil, nil, fmt.Errorf("table %s: desired SQL drops the partitioning the catalog still has; ALTER TABLE … REMOVE PARTITIONING is not yet generated by myschema. Run the REMOVE PARTITIONING by hand and let the next plan reconverge", fqtn)
	}

	curPO, err := parser.ParsePartitionClause(*current)
	if err != nil {
		return nil, nil, fmt.Errorf("table %s: re-parse current partition clause: %w", fqtn, err)
	}
	desPO, err := parser.ParsePartitionClause(*desired)
	if err != nil {
		return nil, nil, fmt.Errorf("table %s: re-parse desired partition clause: %w", fqtn, err)
	}
	// Strategy / expression / column list mismatch → scheme change,
	// out of scope for v1.
	if !partitionHeaderEqual(curPO, desPO) {
		return nil, nil, fmt.Errorf("table %s: partition strategy / expression differs between catalog and desired SQL; partition scheme changes are not yet generated by myschema. Run two separate ALTERs by hand — `ALTER TABLE … REMOVE PARTITIONING` followed by `ALTER TABLE … PARTITION BY …` — and let the next plan reconverge", fqtn)
	}
	// HASH / KEY (incl. LINEAR) — `partitionHeaderEqual` already
	// confirmed Type, IsLinear, KeyAlgorithm, ColList and Expr
	// match, so the only remaining axis is the `PARTITIONS n`
	// count. MySQL has dedicated grammar for this; both
	// directions are row-preserving but data-moving:
	//   - growing → `ALTER TABLE … ADD PARTITION PARTITIONS n`
	//     (n = desired - current).
	//   - shrinking → `ALTER TABLE … COALESCE PARTITION n`
	//     (n = current - desired). Merges the trailing
	//     partitions into the survivors. The slot structure
	//     itself goes away irreversibly (un-COALESCE means
	//     another ALTER that rewrites data again), so it's
	//     gated on `--allow-drop=partition` like RANGE/LIST
	//     DROP — same "destructive / heavy" treatment, just at
	//     the slot level rather than the row level.
	// Cost note: regular HASH / KEY uses the partition-function
	// modulus, so changing the count effectively rewrites the
	// table (most rows shift partition). LINEAR HASH / LINEAR
	// KEY uses a linear-powers-of-two algorithm and only
	// touches partitions adjacent to the change, which the
	// MySQL manual calls out as "much faster" for adding,
	// dropping, merging, and splitting. The diff layer doesn't
	// have to care which one the user picked — the grammar is
	// the same — but the operational cost differs by orders of
	// magnitude on large tables.
	// Equal counts (or both unset) → no-op. The raw-string fast
	// path at the top usually catches that, but `partitionHeaderEqual`
	// lower-cases ColList / Expr identifiers, so an
	// identifier-casing-only diff reaches this branch even though
	// nothing has actually changed.
	if curPO.Type != sqlparser.RangeType && curPO.Type != sqlparser.ListType {
		if curPO.Partitions == desPO.Partitions {
			return nil, nil, nil
		}
		if desPO.Partitions > curPO.Partitions {
			n := desPO.Partitions - curPO.Partitions
			return []string{fmt.Sprintf("ALTER TABLE %s ADD PARTITION PARTITIONS %d;", fqtn, n)}, nil, nil
		}
		n := curPO.Partitions - desPO.Partitions
		coalesce := fmt.Sprintf("ALTER TABLE %s COALESCE PARTITION %d;", fqtn, n)
		if dc.IsDropAllowed("partition") {
			return []string{coalesce}, nil, nil
		}
		return nil, []string{"-- skipped: " + coalesce}, nil
	}

	curDefs := curPO.Definitions
	desDefs := desPO.Definitions

	// Order-preserving subset diff. Each current partition is either
	// kept (matched by the next-unconsumed desired partition) or
	// dropped; anything left in desired after the walk is a suffix
	// add. The four observable outcomes:
	//   - both empty → no-op (catches the equality cases the raw-
	//     string fast path missed because of formatting drift).
	//   - pure ADD (drops empty, adds non-empty) → suffix grow.
	//   - pure DROP (adds empty, drops non-empty) → any subset
	//     dropped while preserving the remaining order; head /
	//     tail / interior drops all generated as
	//     `DROP PARTITION p1, p2, …`.
	//   - drops AND adds both non-empty:
	//     - if the two name lists match position-by-position,
	//       every partition stays in the same slot and the diff
	//       is necessarily an in-place rewrite of one or more
	//       per-partition definitions — a `VALUES …` boundary
	//       tweak, a COMMENT / MAX_ROWS / TABLESPACE change, or
	//       any other per-partition option that round-trips
	//       through vitess's PartitionDefinition formatter.
	//       Generates one `REORGANIZE PARTITION old_i,
	//       old_{i+1}, … INTO (PARTITION old_i …,
	//       PARTITION old_{i+1} …, …)` *per run of consecutive
	//       changed slots*, each row-preserving (REORGANIZE
	//       redistributes rows into the new value boundaries
	//       when those moved). The detailed algorithm — runs,
	//       RANGE cascade, the no-op fallthroughs — lives in
	//       the comment over the `partitionNameListEqual`
	//       branch in `diffPartitions`.
	//     - any other shape (merge / split / interior insert /
	//       reorder / "retention roll-forward") falls through to
	//       error. Disjoint-name detection isn't enough to tell
	//       merge / split / replace apart from a pure retention
	//       discard, and split-point inference is out of scope
	//       for v1, so the user runs the right ALTER (REORGANIZE
	//       with explicit boundaries, or DROP+ADD if discarding
	//       data is intended) by hand.
	// "Pure per-partition definition change" path. When the
	// catalog and desired name lists line up position-by-position
	// (every partition stays in the same slot, every name
	// matches case-insensitively) the diff is necessarily an
	// in-place change to one or more definitions — value
	// boundaries, COMMENT, MAX_ROWS, etc. all flow through
	// `parser.FormatPartitionDefinition`'s identity check.
	//
	// How the REORGANIZE statements are sliced depends on the
	// partition strategy, because the safety constraints
	// differ:
	//
	//   - RANGE / RANGE COLUMNS: emit *one REORGANIZE per run
	//     of consecutive changed slots*. RANGE values are
	//     continuous and bound by per-slot boundaries, so a
	//     value can only move to an adjacent slot when its
	//     boundary shifts — values can't cross over an
	//     unchanged slot in between. Per-run with the boundary
	//     cascade (see below) keeps each statement self-
	//     contained and correct. MySQL's Error 1519 ("When
	//     reorganizing a set of partitions they must be in
	//     consecutive order") only constrains the
	//     partition_names list *within a single REORGANIZE
	//     statement*; multiple REORGANIZE statements in
	//     sequence each with their own consecutive list are
	//     fine. So a "p1 + p3 boundary edit" 5-partition RANGE
	//     table emits two REORGANIZE statements rather than
	//     one giant `REORGANIZE p1, p2, p3, p4 …` that drags
	//     unchanged p2 into the rewrite.
	//
	//   - LIST / LIST COLUMNS: emit *one single-span
	//     REORGANIZE* covering [first..last]. LIST values are
	//     a discrete set per slot, and a value can move
	//     between any two partitions regardless of position —
	//     so a "p0 gains 4, p3 loses 4" cross-flow needs both
	//     ends of the move inside a single REORGANIZE.
	//     Splitting into per-run REORGANIZEs would break MySQL's
	//     value-uniqueness rule (Error 1495 "Multiple
	//     definition of same constant in list partitioning")
	//     on the first statement while the second partition
	//     still owned the value. We could detect cross-flow
	//     and use per-run only for the no-cross-flow case,
	//     but the implementation overhead (per-value owner
	//     tracking, tuple equality for LIST COLUMNS) isn't
	//     worth it — the matched in-between slots get
	//     re-stated unchanged, MySQL no-ops them, and the
	//     resulting ALTER is still proportional to the diff
	//     in real-world usage.
	//
	// RANGE boundary cascade *within each run*: each
	// partition's `VALUES LESS THAN <x>` is also the implicit
	// lower bound of the next partition, so when the run's
	// last slot's upper bound moved AND that slot isn't the
	// final partition, pulling `last+1` into the run re-
	// establishes the boundary alignment with the unchanged
	// tail (otherwise MySQL rejects with "VALUES less than
	// value must be strictly increasing"). Per-partition
	// option-only diffs leave the value range untouched, so
	// the cascade doesn't fire — keeps a metadata-only edit a
	// one-slot REORGANIZE. LIST has no equivalent cascade
	// because `VALUES IN (…)` is a closed set per slot.
	// Cascades from one RANGE run can't extend into the next:
	// the slot the cascade pulls in is by definition matched
	// (otherwise it'd already be part of the current run), and
	// the next run starts at the next changed slot, which is
	// at least one more position over.
	if partitionNameListEqual(curDefs, desDefs) {
		var stmts []string
		switch curPO.Type {
		case sqlparser.RangeType:
			for i := 0; i < len(curDefs); i++ {
				if partitionDefEqual(curDefs[i], desDefs[i]) {
					continue
				}
				first := i
				last := i
				for last+1 < len(curDefs) && !partitionDefEqual(curDefs[last+1], desDefs[last+1]) {
					last++
				}
				if last < len(curDefs)-1 &&
					!partitionValueRangeEqual(curDefs[last], desDefs[last]) {
					last++
				}
				stmts = append(stmts, formatReorganizeRun(fqtn, curDefs, desDefs, first, last))
				i = last
			}
		default:
			first, last := -1, -1
			for i := range curDefs {
				if !partitionDefEqual(curDefs[i], desDefs[i]) {
					if first < 0 {
						first = i
					}
					last = i
				}
			}
			if first >= 0 {
				stmts = append(stmts, formatReorganizeRun(fqtn, curDefs, desDefs, first, last))
			}
		}
		if stmts == nil {
			// Every position compares equal under partitionDefEqual,
			// even though the raw-string fast path didn't catch it.
			// Reachable for: formatter-resolved formatting drift
			// (whitespace, identifier casing inside the partition
			// expression), case-only partition-name diffs like
			// `pAB → PAB` (EqualFold in partitionDefEqual), and LIST
			// `VALUES IN (…)` permutations like `(1,2) → (2,1)`
			// (temporarilySortListValues in partitionDefEqual). All
			// no-ops at the SQL level — emit nothing.
			return nil, nil, nil
		}
		return stmts, nil, nil
	}

	drops, adds := partitionByNameOrderPreserving(curDefs, desDefs)
	if len(drops) > 0 && len(adds) > 0 {
		// Name lists differ by both add(s) and drop(s) — the
		// shape needs more than a per-slot value rewrite (split,
		// merge, reorder, interior insert, retention discard).
		// myschema can't safely infer the right REORGANIZE
		// boundaries from a name-only diff, so the user runs the
		// ALTER by hand.
		return nil, nil, fmt.Errorf("table %s: partition definitions differ in a way the diff layer can't generate — the catalog and desired partition name lists don't line up position-by-position, so this is some shape of split / merge / reorder / interior insert / retention roll-forward. Run REORGANIZE PARTITION (with explicit boundaries) or a DROP + ADD pair (when discarding data is intended) by hand", fqtn)
	}

	var stmts, disallowed []string

	if len(adds) > 0 {
		var b strings.Builder
		b.WriteString("ALTER TABLE ")
		b.WriteString(fqtn)
		b.WriteString(" ADD PARTITION (")
		for i, d := range adds {
			if i > 0 {
				b.WriteString(",\n  ")
			} else {
				b.WriteString("\n  ")
			}
			b.WriteString(parser.FormatPartitionDefinition(d))
		}
		b.WriteString("\n);")
		stmts = append(stmts, b.String())
	}

	if len(drops) > 0 {
		names := make([]string, 0, len(drops))
		for _, d := range drops {
			// Quote through model.Ident so a partition named with a
			// MySQL reserved word or non-safe identifier round-trips
			// correctly. ADD PARTITION already inherits quoting via
			// vitess's PartitionDefinition formatter; DROP PARTITION
			// needs to do it explicitly because we only emit the bare
			// name list.
			names = append(names, model.Ident(d.Name.String()))
		}
		drop := "ALTER TABLE " + fqtn + " DROP PARTITION " + strings.Join(names, ", ") + ";"
		if dc.IsDropAllowed("partition") {
			stmts = append(stmts, drop)
		} else {
			disallowed = append(disallowed, "-- skipped: "+drop)
		}
	}

	return stmts, disallowed, nil
}

// partitionHeaderEqual checks that two PartitionOptions describe the
// same strategy: same Type (RANGE / LIST / HASH / KEY), same column
// list (KEY / RANGE COLUMNS / LIST COLUMNS), same expression (RANGE
// / LIST / HASH), same IsLinear / KeyAlgorithm flags. Definitions
// themselves are compared separately.
func partitionHeaderEqual(a, b *sqlparser.PartitionOption) bool {
	if a == nil || b == nil {
		return a == b
	}
	if a.Type != b.Type || a.IsLinear != b.IsLinear || a.KeyAlgorithm != b.KeyAlgorithm {
		return false
	}
	if !stringSliceEqual(colListNames(a.ColList), colListNames(b.ColList)) {
		return false
	}
	// Compare expressions through vitess's formatter directly. Both
	// AST trees were built by re-parsing the strings already
	// produced by parser.NormalizePartitionOption, which lower-cased
	// function / column identifiers in place — so the formatted
	// outputs already match on identifier casing without us having
	// to re-run anything here. Critically, we must NOT lower-case
	// the formatted string ourselves: that would also collapse
	// string-literal case (`'US'` vs `'us'`) and silently equate
	// real expression changes like `WHEN region='US'` ↔
	// `WHEN region='us'`.
	return formatExpr(a.Expr) == formatExpr(b.Expr)
}

func colListNames(cols sqlparser.Columns) []string {
	out := make([]string, 0, len(cols))
	for _, c := range cols {
		out = append(out, strings.ToLower(c.String()))
	}
	return out
}

func formatExpr(e sqlparser.Expr) string {
	if e == nil {
		return ""
	}
	return sqlparser.String(e)
}

func stringSliceEqual(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// partitionNameListEqual reports whether the two definition slices
// have the same partition names in the same order. Used by the
// REORGANIZE branch to confirm "pure per-partition definition
// change" — every partition that's about to be dropped
// corresponds positionally to one in the add list with the same
// name. Comparison is case-insensitive because partition names
// are MySQL identifiers (case-insensitive at the engine level)
// AND because `parser.NormalizePartitionOption` does NOT lower-
// case partition names — it only lower-cases function /
// column-reference identifiers inside the partition expression.
// Without `EqualFold` here a `pAB → PAB` desired-side rewrite
// would slip past this check and tip the diff into the
// disjoint-name "split / merge / reorder" error branch.
func partitionNameListEqual(a, b []*sqlparser.PartitionDefinition) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if !strings.EqualFold(a[i].Name.String(), b[i].Name.String()) {
			return false
		}
	}
	return true
}

// partitionByNameOrderPreserving walks `cur` once, matching each
// definition against the next-unconsumed entry of `des`. Matched
// pairs are kept; unmatched current entries are added to `drops`;
// any leftover desired entries become `adds`. Order is preserved
// on both sides — the caller treats a "drops + adds both
// non-empty" outcome as an interior reshape (REORGANIZE).
//
// `partitionDefEqual` already accounts for the
// NormalizePartitionOption / ParsePartitionClause round-trip
// (engine strip, identifier lower-casing, etc.) so name+value
// equality here is bytewise on the canonical form.
func partitionByNameOrderPreserving(cur, des []*sqlparser.PartitionDefinition) (drops, adds []*sqlparser.PartitionDefinition) {
	di := 0
	for _, c := range cur {
		if di < len(des) && partitionDefEqual(c, des[di]) {
			di++
			continue
		}
		drops = append(drops, c)
	}
	if di < len(des) {
		adds = append(adds, des[di:]...)
	}
	return drops, adds
}

// formatReorganizeRun renders a single
// `ALTER TABLE … REORGANIZE PARTITION old_first, …, old_last
// INTO (PARTITION old_first …, …, PARTITION old_last …)` for
// one run of consecutive partition slots in `[first, last]`.
// The OLD-name list goes through `model.Ident` so reserved-word
// or non-safe-identifier partition names get back-ticked; the
// INTO bodies go through `parser.FormatPartitionDefinition`
// which delegates name quoting to vitess's own formatter.
//
// Per-slot, the INTO body uses `desDefs[i]` for slots that
// actually changed and `curDefs[i]` for slots that
// `partitionDefEqual` already considers equal but were pulled
// into the run by the RANGE boundary cascade. The cascaded
// slot's body is canonically the same on both sides — the
// only thing that can differ is the partition *name* (case-
// only rename, suppressed by the EqualFold in
// partitionDefEqual). Restating the catalog's body for the
// cascaded slot keeps the "case-only name diff emits no DDL"
// rule honest at the cascaded slot too — without this the
// formatter would leak the desired-side renamed casing into
// the generated REORGANIZE even though MySQL would ignore the
// rename.
func formatReorganizeRun(fqtn string, curDefs, desDefs []*sqlparser.PartitionDefinition, first, last int) string {
	var b strings.Builder
	b.WriteString("ALTER TABLE ")
	b.WriteString(fqtn)
	b.WriteString(" REORGANIZE PARTITION ")
	for i := first; i <= last; i++ {
		if i > first {
			b.WriteString(", ")
		}
		b.WriteString(model.Ident(curDefs[i].Name.String()))
	}
	b.WriteString(" INTO (")
	for i := first; i <= last; i++ {
		if i > first {
			b.WriteString(",\n  ")
		} else {
			b.WriteString("\n  ")
		}
		def := desDefs[i]
		if partitionDefEqual(curDefs[i], desDefs[i]) {
			def = curDefs[i]
		}
		b.WriteString(parser.FormatPartitionDefinition(def))
	}
	b.WriteString("\n);")
	return b.String()
}

// partitionValueRangeEqual reports whether the two definitions
// describe the same value boundary (`VALUES LESS THAN …` or
// `VALUES IN (…)`) — i.e. whether ONLY the per-partition
// options changed (COMMENT / MAX_ROWS / TABLESPACE / …) when
// `partitionDefEqual` already said the full definition differs.
// Used by the RANGE boundary cascade decision: skip the cascade
// when the last changed slot's boundary didn't move.
//
// LIST `VALUES IN (…)` permutations are folded to equal here
// — same set-semantics rule `partitionDefEqual` enforces — so
// the helper is safe to reuse outside the current RANGE-only
// cascade gate without reintroducing the spurious-REORGANIZE
// regression that the temp-sort in `partitionDefEqual` fixed.
func partitionValueRangeEqual(a, b *sqlparser.PartitionDefinition) bool {
	var ar, br *sqlparser.PartitionValueRange
	if a.Options != nil {
		ar = a.Options.ValueRange
	}
	if b.Options != nil {
		br = b.Options.ValueRange
	}
	if ar == nil && br == nil {
		return true
	}
	if ar == nil || br == nil {
		return false
	}
	if restore := temporarilySortValueRangeListValues(ar, br); restore != nil {
		defer restore()
	}
	return sqlparser.String(ar) == sqlparser.String(br)
}

// temporarilySortValueRangeListValues is the
// `temporarilySortListValues` analogue for two
// `*PartitionValueRange` rather than two
// `*PartitionDefinition`. Same mechanic: temp-sort the Range
// slices in place by formatted-string for InType comparison,
// restore on defer so callers' subsequent formatting still
// sees the original AST order.
func temporarilySortValueRangeListValues(a, b *sqlparser.PartitionValueRange) func() {
	if a.Type != sqlparser.InType || b.Type != sqlparser.InType {
		return nil
	}
	savedA := append(sqlparser.ValTuple(nil), a.Range...)
	savedB := append(sqlparser.ValTuple(nil), b.Range...)
	sortValTupleByFormattedString(a.Range)
	sortValTupleByFormattedString(b.Range)
	return func() {
		a.Range = savedA
		b.Range = savedB
	}
}

func partitionDefEqual(a, b *sqlparser.PartitionDefinition) bool {
	if a == nil || b == nil {
		return a == b
	}
	// MySQL identifiers are case-insensitive, and the parser /
	// catalog round-trip preserves whatever case the user wrote
	// — so compare names with EqualFold to match
	// partitionNameListEqual and avoid misclassifying a
	// `pAB → PAB` style diff as a value-change REORGANIZE.
	if !strings.EqualFold(a.Name.String(), b.Name.String()) {
		return false
	}
	// FormatPartitionDefinition includes the partition name in
	// its output, so even after the EqualFold name check above
	// `pAB` and `PAB` would format to different strings and
	// trip a spurious REORGANIZE. Temporarily make b's name
	// match a's so the formatter compares only the bodies; the
	// AST is restored before this function returns.
	savedName := b.Name
	b.Name = a.Name
	defer func() { b.Name = savedName }()
	// LIST `VALUES IN (…)` is a set semantically — reordering
	// the literals doesn't change which rows land in which
	// partition. Without this normaliser the formatted-body
	// comparison below would treat `(2, 1)` vs `(1, 2)` as a
	// real diff and emit a spurious data-moving REORGANIZE.
	// Temp-sort both Range slices in place by formatted-string
	// so the canonical orders match; the AST is restored before
	// this function returns so any later
	// FormatPartitionDefinition call (e.g. building the
	// REORGANIZE INTO list when other slots actually changed)
	// still sees the user's original order.
	if restore := temporarilySortListValues(a, b); restore != nil {
		defer restore()
	}
	return parser.FormatPartitionDefinition(a) == parser.FormatPartitionDefinition(b)
}

func temporarilySortListValues(a, b *sqlparser.PartitionDefinition) func() {
	if a.Options == nil || b.Options == nil ||
		a.Options.ValueRange == nil || b.Options.ValueRange == nil {
		return nil
	}
	return temporarilySortValueRangeListValues(a.Options.ValueRange, b.Options.ValueRange)
}

func sortValTupleByFormattedString(vs sqlparser.ValTuple) {
	sort.Slice(vs, func(i, j int) bool {
		return sqlparser.String(vs[i]) < sqlparser.String(vs[j])
	})
}
