package diff

import (
	"fmt"
	"strings"

	"vitess.io/vitess/go/vt/sqlparser"

	"github.com/winebarrel/myschema/model"
	"github.com/winebarrel/myschema/parser"
)

// diffPartitions compares the partition clauses of `current` and
// `desired` (both already normalised through
// `parser.NormalizePartitionOption`, both stored on
// `model.Table.Partition` as `*string`). Returns the executable
// `ALTER TABLE … ADD/DROP PARTITION` statements, the suppressed
// drops (when `--allow-drop=partition` is unset), and an error
// for any partition diff myschema doesn't generate yet.
//
// v1 scope (this PR):
//
//   - both sides nil → no-op.
//   - both sides set, byte-equal → no-op.
//   - one side nil → error (adding / removing partitioning to/from
//     an existing table is REMOVE PARTITIONING + new PARTITION BY,
//     a future PR).
//   - partition strategy (RANGE/LIST/HASH/KEY/...COLUMNS),
//     expression, or column list differs → error (scheme change
//     is a future PR).
//   - HASH/KEY → error (count operations need their own grammar:
//     COALESCE PARTITION / ADD PARTITION PARTITIONS n; future PR).
//   - RANGE/LIST: definitions are compared positionally.
//     Pure suffix add (current is a prefix of desired) → ADD
//     PARTITION; pure suffix drop (desired is a prefix of
//     current) → DROP PARTITION; anything else (mid-list insert,
//     value change, reorder) → error so the user falls back to
//     manual REORGANIZE.
//
// CAVEATS.md "Partitioning" documents the user-facing rules.
func diffPartitions(fqtn string, current, desired *string, dc DropChecker) ([]string, []string, error) {
	if current == nil && desired == nil {
		return nil, nil, nil
	}
	if current != nil && desired != nil && *current == *desired {
		return nil, nil, nil
	}
	if current == nil || desired == nil {
		return nil, nil, fmt.Errorf("table %s: partition definition differs (one side has no partitioning, the other does); adding or removing partitioning from a managed table is not yet generated by myschema. Run REMOVE PARTITIONING / PARTITION BY by hand and let the next plan reconverge", fqtn)
	}

	curPO, err := parser.ParsePartitionClause(*current)
	if err != nil {
		return nil, nil, fmt.Errorf("table %s: re-parse current partition clause: %w", fqtn, err)
	}
	desPO, err := parser.ParsePartitionClause(*desired)
	if err != nil {
		return nil, nil, fmt.Errorf("table %s: re-parse desired partition clause: %w", fqtn, err)
	}
	// Strategy / expression / column list mismatch → scheme change,
	// out of scope for v1.
	if !partitionHeaderEqual(curPO, desPO) {
		return nil, nil, fmt.Errorf("table %s: partition strategy / expression differs between catalog and desired SQL; partition scheme changes are not yet generated by myschema. Run ALTER TABLE … REMOVE PARTITIONING + PARTITION BY by hand", fqtn)
	}
	// HASH/KEY use count-based grammar (COALESCE PARTITION /
	// ADD PARTITION PARTITIONS n) — different code path, future PR.
	if curPO.Type != sqlparser.RangeType && curPO.Type != sqlparser.ListType {
		return nil, nil, fmt.Errorf("table %s: HASH / KEY partition diffs are not yet generated by myschema (RANGE / LIST only in this version). Run ALTER TABLE … COALESCE PARTITION / ADD PARTITION PARTITIONS by hand", fqtn)
	}

	curDefs := curPO.Definitions
	desDefs := desPO.Definitions

	// Find the longest common prefix by name+value identity. Anything
	// past that prefix is either a suffix add (desired only) or a
	// suffix drop (current only); a mid-list mismatch errors.
	prefix := commonPartitionPrefix(curDefs, desDefs)
	curTail := curDefs[prefix:]
	desTail := desDefs[prefix:]

	// The two tails must be on opposite sides for a clean ADD or
	// DROP. If both have content the change isn't a pure suffix
	// operation — would need REORGANIZE PARTITION (or DROP+ADD
	// across the boundary, which would also drop data).
	if len(curTail) > 0 && len(desTail) > 0 {
		return nil, nil, fmt.Errorf("table %s: partition definitions differ in the middle of the list (not a pure suffix add/drop); REORGANIZE PARTITION generation is not yet implemented. Run the ALTER by hand and let the next plan reconverge", fqtn)
	}

	var stmts, disallowed []string

	if len(desTail) > 0 {
		var b strings.Builder
		b.WriteString("ALTER TABLE ")
		b.WriteString(fqtn)
		b.WriteString(" ADD PARTITION (")
		for i, d := range desTail {
			if i > 0 {
				b.WriteString(",\n  ")
			} else {
				b.WriteString("\n  ")
			}
			b.WriteString(parser.FormatPartitionDefinition(d))
		}
		b.WriteString("\n);")
		stmts = append(stmts, b.String())
	}

	if len(curTail) > 0 {
		names := make([]string, 0, len(curTail))
		for _, d := range curTail {
			// Quote through model.Ident so a partition named with a
			// MySQL reserved word or non-safe identifier round-trips
			// correctly. ADD PARTITION already inherits quoting via
			// vitess's PartitionDefinition formatter; DROP PARTITION
			// needs to do it explicitly because we only emit the bare
			// name list.
			names = append(names, model.Ident(d.Name.String()))
		}
		drop := "ALTER TABLE " + fqtn + " DROP PARTITION " + strings.Join(names, ", ") + ";"
		if dc.IsDropAllowed("partition") {
			stmts = append(stmts, drop)
		} else {
			disallowed = append(disallowed, "-- skipped: "+drop)
		}
	}

	return stmts, disallowed, nil
}

// partitionHeaderEqual checks that two PartitionOptions describe the
// same strategy: same Type (RANGE / LIST / HASH / KEY), same column
// list (KEY / RANGE COLUMNS / LIST COLUMNS), same expression (RANGE
// / LIST / HASH), same IsLinear / KeyAlgorithm flags. Definitions
// themselves are compared separately.
func partitionHeaderEqual(a, b *sqlparser.PartitionOption) bool {
	if a == nil || b == nil {
		return a == b
	}
	if a.Type != b.Type || a.IsLinear != b.IsLinear || a.KeyAlgorithm != b.KeyAlgorithm {
		return false
	}
	if !stringSliceEqual(colListNames(a.ColList), colListNames(b.ColList)) {
		return false
	}
	// Compare expressions through vitess's formatter directly. Both
	// AST trees were built by re-parsing the strings already
	// produced by parser.NormalizePartitionOption, which lower-cased
	// function / column identifiers in place — so the formatted
	// outputs already match on identifier casing without us having
	// to re-run anything here. Critically, we must NOT lower-case
	// the formatted string ourselves: that would also collapse
	// string-literal case (`'US'` vs `'us'`) and silently equate
	// real expression changes like `WHEN region='US'` ↔
	// `WHEN region='us'`.
	return formatExpr(a.Expr) == formatExpr(b.Expr)
}

func colListNames(cols sqlparser.Columns) []string {
	out := make([]string, 0, len(cols))
	for _, c := range cols {
		out = append(out, strings.ToLower(c.String()))
	}
	return out
}

func formatExpr(e sqlparser.Expr) string {
	if e == nil {
		return ""
	}
	return sqlparser.String(e)
}

func stringSliceEqual(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// commonPartitionPrefix returns how many leading partition definitions
// are byte-identical (name + serialised body) between the two slices.
// Both sides have already been through NormalizePartitionOption /
// ParsePartitionClause, so per-partition `engine` options have been
// stripped and identifier casing matches.
func commonPartitionPrefix(a, b []*sqlparser.PartitionDefinition) int {
	n := len(a)
	if len(b) < n {
		n = len(b)
	}
	for i := 0; i < n; i++ {
		if !partitionDefEqual(a[i], b[i]) {
			return i
		}
	}
	return n
}

func partitionDefEqual(a, b *sqlparser.PartitionDefinition) bool {
	if a == nil || b == nil {
		return a == b
	}
	if a.Name.String() != b.Name.String() {
		return false
	}
	return parser.FormatPartitionDefinition(a) == parser.FormatPartitionDefinition(b)
}
